// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: db.proto

#include "db.pb.h"
#include "db.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace db {
namespace grpc {

static const char* DBService_method_names[] = {
  "/db.grpc.DBService/CreateTable",
};

std::unique_ptr< DBService::Stub> DBService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DBService::Stub> stub(new DBService::Stub(channel));
  return stub;
}

DBService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_CreateTable_(DBService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DBService::Stub::CreateTable(::grpc::ClientContext* context, const ::db::grpc::CreateTableParam& request, ::db::grpc::CreateTableResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CreateTable_, context, request, response);
}

void DBService::Stub::experimental_async::CreateTable(::grpc::ClientContext* context, const ::db::grpc::CreateTableParam* request, ::db::grpc::CreateTableResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateTable_, context, request, response, std::move(f));
}

void DBService::Stub::experimental_async::CreateTable(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::db::grpc::CreateTableResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CreateTable_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::db::grpc::CreateTableResponse>* DBService::Stub::AsyncCreateTableRaw(::grpc::ClientContext* context, const ::db::grpc::CreateTableParam& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::db::grpc::CreateTableResponse>::Create(channel_.get(), cq, rpcmethod_CreateTable_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::db::grpc::CreateTableResponse>* DBService::Stub::PrepareAsyncCreateTableRaw(::grpc::ClientContext* context, const ::db::grpc::CreateTableParam& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::db::grpc::CreateTableResponse>::Create(channel_.get(), cq, rpcmethod_CreateTable_, context, request, false);
}

DBService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DBService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DBService::Service, ::db::grpc::CreateTableParam, ::db::grpc::CreateTableResponse>(
          std::mem_fn(&DBService::Service::CreateTable), this)));
}

DBService::Service::~Service() {
}

::grpc::Status DBService::Service::CreateTable(::grpc::ServerContext* context, const ::db::grpc::CreateTableParam* request, ::db::grpc::CreateTableResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace db
}  // namespace grpc

